### ISSUE TITLE
Component Images

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/see-like-a-bat#1]
Hi @samalderhyde,
I'm going to need a couple of new components for this one - a vibration motor and an Ultrasonic distance sensor.
I've still to do the second worksheet yet, so awhile before I'm ready to publish though.

**Comment by samalderhyde** [comment]
No probs

**Comment by samalderhyde** [comment]
I'll make a start on the two diagrams in worksheet 1 too

**Comment by MarcScott** [comment]
Cheers. I've three hand-drawn diagrams in there that could probably benefit from being redrawn by you. They show resistors and voltages. Would you be able to do these in a hand drawn style?

Also need a couple of resistor drawing - 1.2k (brown-red-red) and 2.2k (red-red-red).

Thanks again
