### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/see-like-a-bat#2]
Hi @LornaLynch or @lauraclay 
Do you think I could get a copy edit on this. No rush - Sam is working on the diagrams.

Thanks again

**Comment by LornaLynch** [comment]
I can get onto this in a bit :)

**Comment by LornaLynch** [comment]
All done, @MarcScott: there are still Fritzing diagrams in the resource, but I'm guessing you're well aware of this!

**Comment by MarcScott** [comment]
Thanks @LornaLynch that's great. Sam's working on the drawings for me.
